version: '3.4'

services:
  #Eureka
  naming-server:
    image: msodrejr/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - msjr-network
  #API-Gateway
  api-gateway:
    image: msodrejr/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - msjr-network
  #services
  cambio-service:
    image: msodrejr/cambio-service:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - zipkin-server
      - rabbit-mq
      - naming-server
      - cambio-db
    environment:
      TZ: America/Sao_Paulo
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL-false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL-false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: admin123
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - msjr-network
  book-service:
    image: msodrejr/book-service:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8100:8100
    depends_on:
      - zipkin-server
      - rabbit-mq
      - naming-server
      - book-db
    environment:
      TZ: America/Sao_Paulo
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book_service?useSSL-false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3310/book_service?useSSL-false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: admin123
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - msjr-network
  #Databases
  cambio-db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3308
    expose:
      - 3308
    depends_on:
      - naming-server
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_ROOT_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    networks:
      - msjr-network
  book-db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3310:3310
    expose:
      - 3310
    depends_on:
      - naming-server
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_ROOT_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    networks:
      - msjr-network
  #mensageria
  rabbit-mq:
    image: rabbitmq:3.8.14-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - msjr-network
  #Observability
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    restart: always
    ports:
      - 9411:9411
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - msjr-network
networks:
  msjr-network:
    driver: bridge